version: '3'

services:
  redis:
    image: redis:latest

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db.py:/docker-entrypoint-initdb.d/init_db.py

  gunicorn:
    build: .
    depends_on:
      - redis
      - postgres
    environment:
      DATABASE_URL: postgres://admin:admin@postgres/test
      
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - gunicorn

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - "5540:5540"
    environment:
      REDISINSIGHT_ENABLE_AUTH: "false" 

networks:
  default:
    driver: bridge

volumes:
  postgres_data:
